### ISSUE TITLE
Model should be configurable

### ISSUE THREAD

**Issue by dalehurley** [hero-page/hero-ai-package-creator#1]
The model is currently hardcoded to "get-4", line 19 @hero-page/hero-ai-package-creator/toolkit/gpt.js

This should configurable e.g. 
```
const MODEL = options.model;
...
const completion = await openai.createChatCompletion({
    model: MODEL,
    messages: [{role: "user", content: options.prompt}],
});
```

**Comment by kingmeers** [comment]
You're right @dalehurley! Will update this 😊

Fixed in [20d91e21ce60e4b626031873016d8328ff7cae15](https://github.com/hero-page/hero-ai-package-creator/commit/20d91e21ce60e4b626031873016d8328ff7cae15)
